---
title: "R Notebook"
#output: html_notebook
---

SHould we plot a DFA?

```{r}

pacman::p_load(tidyverse,  here, MASS)


scale2 <- function(x, na.rm = TRUE) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm)

here::i_am("README.md")
here()

dat <- read_csv(here("Data", "Extant_Master.csv")) %>% 
  drop_na(Loc_Ord2) %>% 
  mutate(Family = case_when(
    Family == 'Callitrichidae (Cebidae)' ~ 'Callitrichidae',
    Family == 'Prionodontidae (Viverridae)' ~ 'Prionodontidae',
    TRUE ~ Family)) %>% 
  mutate(Loc_Ord2 = as.ordered(Loc_Ord2),
         Loc_Ord2 = fct_relevel(Loc_Ord2, c("B","T","Sc","A")))


dat2 <- dat %>% group_by(Genus_species, Loc_Ord2, Loc_bin) %>% summarise_at(vars(Sl:lsCl), mean, na.rm = TRUE) %>% 
  ungroup() %>% 
  mutate(Loc_Ord2 = as.ordered(Loc_Ord2),
         Loc_Ord2 = fct_relevel(Loc_Ord2, c("B","T","Sc","A")))


var_complete <- read_rds(here("Data", "var_complete.Rds"))
```

## Ordination All Non-Missing Vars

### DFA no-missing
```{r}
model <- lda(Loc_Ord2 ~  Sl + Hl + Hsw + Hdw + Uol + Ul + Rl + Fl + Fsw + Fdw + Tl + Tmw + SI+HRI + HEB + OLI + BI + IM + FRI + FEB+CI + TRI + lsSl + lsHl + lsHsw + lsHdw + lsUol+lsUl + lsRl + lsFl + lsFsw + lsFdw + lsTl + lsTmw, 
                   data = dat2, 
                   na.action = na.omit) 

pred <- predict(model)


dat2 <- dat2 %>% bind_cols(pred$x) 

hull1 <- dat2 %>% 
  group_by(Loc_Ord2) %>% 
  slice(chull(LD1, LD2))

p1 <- dat2 %>% ggplot(aes(x = LD1, y = LD2, color = Loc_Ord2)) + 
    geom_polygon(aes(fill = Loc_Ord2, 
                   color = Loc_Ord2),
               data = hull1, 
               alpha = 0.2, 
               show.legend = F,
               size = 0.2) +
  geom_point(alpha = 0.7) + 
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  theme_bw()
```

#### Confusion Matrix

```{r}
confusion <- function(actual, predicted, names = NULL, printit = TRUE,
 prior = NULL) {
 if (is.null(names))
 names <- levels(actual)
 tab <- table(actual, predicted)
 acctab <- t(apply(tab, 1, function(x) x/sum(x)))
 dimnames(acctab) <- list(Actual = names, "Predicted (cv)" = names)
 if (is.null(prior)) {
 relnum <- table(actual)
 prior <- relnum/sum(relnum)
 acc <- sum(tab[row(tab) == col(tab)])/sum(tab)
 }
 else {
 acc <- sum(prior * diag(acctab))
 names(prior) <- names
 }
 if (printit)
 print(round(c("Overall accuracy" = acc, "Prior frequency" = prior),
 4))
 if (printit) {
 cat("\nConfusion matrix", "\n")
 print(round(acctab, 4))
 }
 invisible(acctab)
 }
```

```{r}
model <- lda(Loc_Ord2 ~  Sl + Hl + Hsw + Hdw + Uol + Ul + Rl + Fl + Fsw + Fdw + Tl + Tmw + SI+HRI + HEB + OLI + BI + IM + FRI + FEB+CI + TRI + lsSl + lsHl + lsHsw + lsHdw + lsUol+lsUl + lsRl + lsFl + lsFsw + lsFdw + lsTl + lsTmw, 
                   data = dat2, 
                   na.action = na.omit,
             CV = TRUE) 

confusion(dat2$Loc_Ord2, model$class)
```


### PCA No Missing
```{r}
mod2 <- prcomp(~  Sl + Hl + Hsw + Hdw + Uol + Ul+Rl + Fl + Fsw + Fdw + Tl + Tmw + SI+HRI + HEB + OLI + BI + IM + FRI + FEB+CI + TRI + lsSl + lsHl + lsHsw + lsHdw + lsUol+lsUl + lsRl + lsFl + lsFsw + lsFdw + lsTl + lsTmw, data = dat2, scale.=TRUE)

dat2 <- dat2 %>% bind_cols(mod2$x)

hull2 <- dat2 %>% 
  group_by(Loc_Ord2) %>% 
  slice(chull(PC1, PC2))

p2 <- dat2 %>% ggplot(aes(x = PC1, y = PC2, color = Loc_Ord2)) + 
  geom_polygon(aes(fill = Loc_Ord2, 
                   color = Loc_Ord2),
               data = hull2, 
               alpha = 0.2, 
               show.legend = F,
               size = 0.2) +
  geom_point(alpha = 0.7) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2") + theme_bw()
```

### Plot
```{r}
library(patchwork)

p1 / p2

ggsave(here("Plots", "LD_PC.pdf"), height = 6, width = 4.5)
```






## Ordination Important Vars
## No missing data
```{r}
rm(dat2)
```


```{r}

dat2 <- dat %>% group_by(Genus_species, Loc_Ord2, Loc_bin) %>% summarise_at(vars(Sl:lsCl), mean, na.rm = TRUE) %>% 
  ungroup() %>% 
  mutate(Loc_Ord2 = as.ordered(Loc_Ord2),
         Loc_Ord2 = fct_relevel(Loc_Ord2, c("B","T","Sc","A")))
```

### DFA important!
```{r}
model <- MASS::lda(Loc_Ord2 ~    Hl + OLI +  Rl + Uol + Fl + Ul, 
                   data = dat2) 

pred <- predict(model)


dat2 <- dat2 %>% bind_cols(pred$x) 

hull1 <- dat2 %>% 
  group_by(Loc_Ord2) %>% 
  slice(chull(LD1, LD2))

p1 <- dat2 %>% ggplot(aes(x = LD1*(-1), y = LD2*(-1), color = Loc_Ord2)) + 
    geom_polygon(aes(fill = Loc_Ord2, 
                   color = Loc_Ord2),
               data = hull1, 
               alpha = 0.2, 
               show.legend = F,
               size = 0.2) +
  geom_point(alpha = 0.7) + 
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  theme_bw()
```

#### Confusion Matrix

```{r}

model <- MASS::lda(Loc_Ord2 ~    Hl + OLI +  Rl + Uol + Fl + Ul, 
                   data = dat2, CV = T) 

confusion(dat2$Loc_Ord2, model$class)
```


### PCA No Missing
```{r}
mod2 <- prcomp(~   Hl + OLI +  Rl + Uol + Fl + Ul, data = dat2, scale.=TRUE)

dat2 <- dat2 %>% bind_cols(mod2$x)

hull2 <- dat2 %>% 
  group_by(Loc_Ord2) %>% 
  slice(chull(PC1, PC2))

p2 <- dat2 %>% ggplot(aes(x = PC1, y = PC2*(-1), color = Loc_Ord2)) + 
  geom_polygon(aes(fill = Loc_Ord2, 
                   color = Loc_Ord2),
               data = hull2, 
               alpha = 0.2, 
               show.legend = F,
               size = 0.2) +
  geom_point(alpha = 0.7) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2") + theme_bw()
```

### Plot
```{r}
library(patchwork)

p1 / p2

ggsave(here("Plots", "LD_PC_Important.pdf"), height = 6, width = 4.5)
```

