nm_change = function(df){
  {df} %>% mutate(var = case_when(
                       var == "Hl"  ~ "Humerus Length",
                       var == "Uol"  ~ "Olecranon Length",
                       var == "Rl" ~ "Radius Length",
                       var == "Fl"  ~ "Femur Length",
                       var == "Ppl" ~ "Proximal Phalanx Length",
                       var == "Ipl" ~ "Intermediate Phalanx Length",
                       var == "Ipw"  ~ "Intermediate Phalanx Width",
                       var == "Dpl"  ~ "Distal Phalanx Length",
                       var == "Dpw" ~ "Distal Phalanx Length",
                       var == "Mtl"  ~ "Metatarsal Length",
                       var == "Mtw" ~ "Metatarsal Width",
                       var == "Pipl" ~ "Intermediate Phalanx Length Pes",
                       var == "Pipw" ~ "Intermediate Phalanx Width Pes",
                       var == "HRI" ~ "Humeral Robustness Index",
                       var == "HPI" ~ "Proximal Humeral Index",
                       var == "HEB" ~ "Humeral Epicondyle Index",
                       var == "HHRI" ~ "Humeral Head Index",
                       var == "OLI"  ~ "Olecranon Process Index",
                       var == "PRTI"  ~ "Palm Robustness Index",
                       var == "MANUS" ~ "Manus Proportion Index Proximal",
                       var == "MANUS2"  ~ "Manus Proportion Index Intermediate",
                       var == "MANUS3"  ~ "Manus Phalanges Idex",
                       var == "IRI" ~ "Illium Robustness Index",
                       var == "FRI" ~ "Femoral Robustness Index",
                       var == "FEB" ~ "Femoral Epicondyle Index",
                       var == "CI" ~ "Crural Index",
                       var == "TRI"  ~ "Tibial Robustness Index",
                       var == "PR"  ~ "Pelvic Index",
                       var == "PES" ~ "Pes Proportion Index Proximal",
                       var == "PES2"  ~ "Pes Proportion Index Intermediate",
                       var == "Ul" ~ "Ulna Length",
                       var == "Cal" ~ "Calcaneal Body Length",
                       var == "Anl" ~ "Astragular Neck Length",
                       var == "Ppl" ~ "Proximal Phalanx Length Pes",
                       var == "Fbmw" ~ "Fibula Midshaft Diameter",
                       var == "Fhd" ~ "Femoral Head Diameter",
                       var == "HHW" ~ "Humeral Head Index",
                       var == "IM" ~ "Intermembral Index",
                       var == "MRI" ~ "Metacarpal Robustness Index",
                       var == "Hhl" ~ "Humeral Head Length",
                       var == "Fbl" ~ "Fibula Length",
                       var == "Cl" ~ "Calcaneal Length",
                       var == "Isl" ~ "Ischium Length",
                       var == "Tpw" ~ "Tibial Proximal End Width",
                       TRUE ~ NA)
                      ) 
}