---
title: "Ordinal Classification"
output: html_notebook
---

### Load packages and functions  
```{r message = FALSE, warning=FALSE, include = FALSE}

pacman::p_load(tidyverse,  brms, cmdstanr, kableExtra, here, ape, tidybayes, patchwork, glue)

options(brms.backend = "cmdstanr")

scale2 <- function(x, na.rm = TRUE) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm)

here::i_am("README.md")
here()

var_complete <- read_rds(here("Data", "var_complete.Rds"))
var_missing <- read_rds(here("Data", "var_missing.Rds"))

source(here("Code","Name_Change.R"))
```

### Load data  
All data loading and wrangling in `Code/Data_Load.Rmd`
```{r}
dat <- read_csv(here("Data", "Extant_Master.csv")) %>% 
  drop_na(Loc_Ord2) %>% 
  mutate(Family = case_when(
    Family == 'Callitrichidae (Cebidae)' ~ 'Callitrichidae',
    Family == 'Prionodontidae (Viverridae)' ~ 'Prionodontidae',
    TRUE ~ Family)) %>% 
  mutate(Loc_Ord2 = as.ordered(Loc_Ord2),
         Loc_Ord2 = fct_relevel(Loc_Ord2, c("B","T","Sc","A")))


#species in dataset
spp_obs <- dat$Taxon_Upham_style %>% unique()

#Color palette
pal = c('#62361B', '#f48a1a', '#e6ab02', '#66a61e', '#31c1bb', '#0d57ff', '#5e1ea6', '#f9581c' , '#f384f8')
```

### Load Tree & Get Cor Matrix

```{r}
tr <- ape::read.nexus(
  here("Data","MCC_Upham_all_mammals.nex"))
tr <- ape::keep.tip(tr, spp_obs)
A <- ape::vcv.phylo(tr, corr = TRUE)
```

## Description of Missing Data
Follows `Binary_Missing_Models.Rmd`

```{r}
var_complete <- read_rds(here("Data", "var_complete.Rds"))
var_missing <- read_rds(here("Data", "var_missing.Rds"))
```



#### Get Prior

```{r message = FALSE, warning=FALSE, include = FALSE}

p1 <- get_prior(Loc_Ord2 ~ Sl * log_Mass + (1 | Genus_species) +  (1|gr(Taxon_Upham_style, cov = A)),
  data2 = list(A = A),
           family = cumulative(),
           data = dat) %>% 
    mutate(
      prior = case_when(
        class == "b"  ~ "normal(0, 2)",
        class == "sd" ~ "normal(0, 0.3)",
        class == "Intercept" ~ "normal(0, 0.5)",
        TRUE ~ prior
      )
    )
```


```{r message = FALSE, warning=FALSE, include = FALSE, cache=TRUE}
#initial fit
mm <- brm(Loc_Ord2 ~ Sl * log_Mass + (1 | Genus_species) +  (1|gr(Taxon_Upham_style, cov = A)),
          data2 = list(A = A),
          family = cumulative(),
          data = dat, refresh = 0, cores = 4,
          prior = p1)
```




```{r}
pal = c('#62361B', '#f48a1a', '#e6ab02', '#66a61e', '#31c1bb', '#0d57ff', '#7570b3')
plot(conditional_effects(mm, categorical = TRUE), plot = F)[[1]] +
  scale_fill_manual(values = pal) +
  scale_color_manual(values = pal)
```

## Log Mass Loop

```{r  message = FALSE, warning=FALSE, results = 'hide'}

list_o_lm <- vector(mode ="list")

for(i in var_complete){
  list_o_lm[[i]]<- update(mm,
                         formula=(paste0("Loc_Ord2 ~", i, "*log_Mass+(1|Genus_species)+(1|gr(Taxon_Upham_style,cov = A))")),
                         family = cumulative(),
                         newdata=dat,
                         refresh = 0,
                         cores = 4,
                         data2 = list(A = A),
                         prior = p1
                         ) 
}

```

#### Log Mass Missing Loop

```{r  message = FALSE, warning=FALSE, results = 'hide'}

#var1 <- c("PES2")

for(i in var_missing){
  ord_mod <-  bf(paste0("Loc_Ord2 ~ mi(", i, ")*log_Mass+(1|Genus_species)+(1|gr(Taxon_Upham_style,cov = A))")) + cumulative()
  imp_mod <- bf(paste0(i,"| mi() ~ log_Mass + Sl +  
       Hl + Hsw + Hdw + Uol + Ul + Rl + 
       Fl + Fsw + Fdw + Tl + Tmw + 
       (1|gr(Taxon_Upham_style, cov = A))")) + gaussian()
  m_form <- ord_mod + imp_mod + set_rescor(FALSE)
  
  pri <- get_prior(m_form,
  data2 = list(A = A),
           data = dat) %>% 
  mutate(
    prior = case_when(
      class == "b"  ~ "normal(0, 2)",
      class == "sd" ~ "normal(0, 0.3)",
      class == "Intercept" ~ "normal(0, 0.5)",
      class == "sigma" ~ "normal(0, 0.5)",
      TRUE ~ prior
      ))
  
    list_o_lm[[i]]<- brm(m_form,
                         data=dat,
                         refresh = 0,
                         cores = 4,
                         data2 = list(A = A),
                         prior = pri,
                         seed = 145
                         ) 
}

list_o_lm %>% write_rds(here("Data","O_lm_int_mods_mis.Rds"))
```


## Geometric Mean Loop

```{r  message = FALSE, warning=FALSE, results = 'hide'}

list_o_gm <- vector(mode ="list")

for(i in var_complete){
  list_o_gm[[i]]<- update(mm,
                         formula=(paste0("Loc_Ord2 ~", i, "*log_gm+(1|Genus_species)+(1|gr(Taxon_Upham_style,cov = A))")),
                         family = cumulative(),
                         newdata=dat,
                         refresh = 0,
                         cores = 4,
                         data2 = list(A = A),
                         prior = p1
                         ) 
}

```

#### Geo Mean Mass Missing Loop

```{r  message = FALSE, warning=FALSE, results = 'hide'}

for(i in var_missing){
  ord_mod <-  bf(paste0("Loc_Ord2 ~ mi(", i, ")*log_gm+(1|Genus_species)+(1|gr(Taxon_Upham_style,cov = A))")) + cumulative()
  imp_mod <- bf(paste0(i,"| mi() ~ log_gm + Sl +  
       Hl + Hsw + Hdw + Uol + Ul + Rl + 
       Fl + Fsw + Fdw + Tl + Tmw + 
       (1|gr(Taxon_Upham_style, cov = A))")) + gaussian()
  m_form <- ord_mod + imp_mod + set_rescor(FALSE)
  
  pri <- get_prior(m_form,
  data2 = list(A = A),
           data = dat) %>% 
  mutate(
    prior = case_when(
      class == "b"  ~ "normal(0, 2)",
      class == "sd" ~ "normal(0, 0.3)",
      class == "Intercept" ~ "normal(0, 0.5)",
      class == "sigma" ~ "normal(0, 0.5)",
      TRUE ~ prior
      ))
  
    list_o_gm[[i]]<- brm(m_form,
                         data=dat,
                         refresh = 0,
                         cores = 4,
                         data2 = list(A = A),
                         prior = pri,
                         seed = 145
                         ) 
}

list_o_gm %>% write_rds(here("Data","O_gm_int_mods_mis.Rds"))
```

