---
title: "Ordinal Conditional Effects"
output: html_notebook
---



# Ordinal Cond Effects Plots 

```{r message = FALSE, warning=FALSE, include = FALSE}

pacman::p_load(tidyverse, brms, here,tidybayes, patchwork, ggthemes, scico)

options(brms.backend = "cmdstanr")

scale2 <- function(x, na.rm = TRUE) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm)

here::i_am("README.md")
here()

var_complete <- read_rds(here("Data", "var_complete.Rds"))
var_missing <- read_rds(here("Data", "var_missing.Rds"))

source(here("Code","Name_Change.R"))

# Models

list_o_lm <- read_rds(here("Data","O_lm_int_mods_mis.Rds"))
list_o_gm <- read_rds(here("Data","O_gm_int_mods_mis.Rds"))
```



some colors
```{r}
pal = c('#66a61e', '#7570b3',  '#e6ab02', '#62361B')

binpal = c('#66a61e','#5e1ea6')#5e1ea6

cols = c("#7570b3" ,  "#85D4E3" , "#0D7E9A",'#f5f5cb', '#c7e6d4', '#8cd2cd', '#55c3cf', '#3fa4b0', '#187389','#f48a1a', '#e6ab02', '#66a61e', '#85D4E3', '#0D7E9A', '#7570b3','#f6d03d', '#fe7b30', '#ef4a27', '#f384f8', '#625afc', '#0d57ff', '#47a7ff','#5771ff', '#6bae9e', '#31c1bb', '#7af1e1', '#d5e1af', '#f48130','#C60C30', '#00A1DE', '#62361B', '#009B3A', '#f9581c', '#522398', '#E27EA6', '#F9E300', '#565A5C')
# myradar colors
radpal = c("#a7034f", "#ef2b02", "#de8d00", "#078e91")
radpal2 = c("#a7034f", "#ef2b02", "#de8d00", "#738E49", "#078e91")

pal2 <- LaCroixColoR::lacroix_palette("Orange", n = 5, type = "continuous")[1:4]
pal3 <- LaCroixColoR::lacroix_palette("Orange", n = 10, type = "continuous")[c(2,5,6,8)]
ibm <- c('#785EF0', '#648FFF', '#DC267F', '#FE6100')

d2 <- c('#a6761d','#d95f02','#7570b3','#1b9e77')
```

## Plotting Function
```{r}

conditions <- data.frame(log_Mass = c(-1.5, 0, 1.5))

ord_plot <- function(mod, effect
                    # title
                     ){
xaxis   <- {{effect}}   
yaxis   <- "Probability"

conditional_effects({{mod}}, 
                          prob = 0.89, 
                          conditions = conditions, categorical = T,
                    resolution = 200, resp = 'LocOrd2',
                          effects= paste(xaxis))[[1]] %>% 
  #extract conditional effects data frame
  as_tibble() %>% 
    mutate(log_Mass = factor(log_Mass, 
                                    levels = c("-1.5", "0", "1.5"),
                                    labels = c("Low Mass", "Mean Mass", "High Mass"))) %>% 
  #rename the objects in the conditional effects df
  rename(Probability = estimate__) %>% 
ggplot(aes(x = .data[[xaxis]], y = Probability, group = cats__)) +
 geom_ribbon(aes(ymin = lower__, 
                  ymax = upper__, 
                  fill = cats__), 
              alpha=0.2) +
  geom_vline(xintercept = 0, linetype = 2, size = 0.1) +
  geom_line(size=1, 
            aes(color=cats__,  alpha = abs(.data[[xaxis]]))) +
  scale_alpha(range = c(1, 0.1), guide = 'none') +
  facet_wrap(~ log_Mass, 
             ncol = 3) +
  #labs(subtitle = "log_Ppl_length") + 
 #scico::scale_fill_scico_d(palette = "hawaii", 
 #                          begin  = 0, 
 #                          end = 0.88, 
 #                          name = "Locomotor\nMode") +
 #scico::scale_color_scico_d(palette = "hawaii", 
 #                          begin  = 0, 
 #                          end = 0.88, 
 #                           name = "Locomotor\nMode") +
  scale_fill_manual(#values = pal3, 
                    values = d2, 
                            name = "Ordered\nLocomotor\nMode") +
  scale_color_manual(#values = pal3, 
                     values = d2, 
                            name = "Ordered\nLocomotor\nMode") +
  theme_classic() +
  ylim(0, 1) + #xlim(-3,3) +
  guides(colour = guide_legend(reverse=T,
                               #title.theme = element_text(size = 7.5),
                               override.aes = list(size = 1)),
         fill = guide_legend(reverse=T,
                             #title.theme = element_text(size = 7.5),
                             override.aes = list(size = 1))) + 
  theme( panel.grid.major = element_blank(), 
         panel.grid.minor = element_blank(),
         strip.background = element_blank(),
         #strip.text.x = element_text(size = 6, margin=margin(b=0.9)),
         panel.border = element_rect(colour = "black", 
                                     fill = NA,
                                     linewidth = rel(0.8)),
         axis.line = element_line(colour = "NA"),
         #axis.text.y = element_text(size=rel(0.5)),
         #axis.text.x = element_text(size=rel(0.5)),
         axis.ticks = element_line(linewidth = rel(0.25)),
         axis.ticks.length =  unit(0.5, "pt"),
         #legend.text=element_text(size=rel(0.7)),
         legend.key = element_rect(color = NA),
         #legend.key.size =    unit(.95, "lines"),
        # axis.title.y = element_text(size = 6, margin=margin(0,-2,0,-10)),
         #axis.title.x = element_text(size = 6, margin=margin(0,0,-3,0)),
        # plot.subtitle=element_text(size=8, margin=margin(-20,0,3.2,0)),
         legend.box.margin = unit(c(-0.5, 0, 0, 0), "lines"),
         plot.margin = unit(c(0.2, 0, 0.3, 0), "lines")
         )
}

```

```{r}
ord_plot(list_o_lm$Hl, "Hl")
ord_plot(list_o_lm$lsRl, "lsRl")
ord_plot(list_o_lm$lsUol, "lsUol")
ord_plot(list_o_lm$MANUS, "MANUS")
ord_plot(list_o_lm$HPI, "HPI")
ord_plot(list_o_lm$PES, "PES")
ord_plot(list_o_lm$OLI, "OLI")
ord_plot(list_o_lm$HRI, "HRI")
```





