---
title: "Phylogenetic Signal"
output: html_notebook
---

Testing Phylogenetic Signal in the Regressions

## Load
```{r}
pacman::p_load(tidyverse, googlesheets4, brms, cmdstanr, here, tidybayes, patchwork)

options(brms.backend = "cmdstanr")

scale2 <- function(x, na.rm = TRUE) (x - mean(x, na.rm = TRUE)) / sd(x, na.rm)

here::i_am("README.md")
here()

list_b_lm <- read_rds(here("Data","B_lm_mods_mis.Rds")) 
```

## Phylo Signal Practice

What is phylo signal here? I think I need to incorperate sigma, phylo, and species

Test with Humerus length and MANUS

Turns out that the phylo signal is the same for all the measurements. The phylo_sd is always around 4.7, and the species_sd is always around 2.5

```{r}
mHl <- list_b_lm$Hl

mUol <- list_b_lm$Uol

mMAN <- list_b_lm$MANUS

get_variables(mMAN)[1:25]
```


```{r}
# Hl phylo signal
hyp <- "sd_Taxon_Upham_style__Intercept^2 / (sd_Taxon_Upham_style__Intercept^2 + sd_Genus_species__Intercept^2) = 0"
hyp1 <- hypothesis(mHl, hyp, class = NULL)

hyp <- "sd_Taxon_Upham_style__Intercept^2 / (sd_Taxon_Upham_style__Intercept^2 + sd_Genus_species__Intercept^2) = 0"
hyp2 <- hypothesis(mUol, hyp, class = NULL)

#MANUS phylo signal
hyp_mi <- "sd_Taxon_Upham_style__Locbin_Intercept^2 / (sd_Taxon_Upham_style__Locbin_Intercept^2  + sd_Genus_species__Locbin_Intercept^2) = 0"
hyp2 <- hypothesis(mMAN, hyp_mi, class = NULL)

# Estimate of missing MANUS phylo signal
hyp_mi2 <- "sd_Taxon_Upham_style__MANUS_Intercept^2 / (sd_Taxon_Upham_style__MANUS_Intercept^2 + sigma_MANUS^2) = 0"
hyp3 <- hypothesis(mMAN, hyp_mi2, class = NULL)

# Uol phylo signal
hyp <- "sd_Taxon_Upham_style__Intercept^2 / (sd_Taxon_Upham_style__Intercept^2 + sd_Genus_species__Intercept^2) = 0"
hyp4 <- hypothesis(mUol, hyp, class = NULL)

p1 <- plot(hyp1, plot = FALSE)[[1]] + theme_bw() + xlim(0,1)
p2 <- plot(hyp2, plot = FALSE)[[1]] + theme_bw() + xlim(0,1)
p3 <- plot(hyp3, plot = FALSE)[[1]] + theme_bw() + xlim(0,1)
p4 <- plot(hyp4, plot = FALSE)[[1]] + theme_bw() + xlim(0,1)

(p1 | p4) / (p2 | p3)
p1 / p2
```

