---
title: "Outlines and Notes for book chapter"
output:
  html_document:
    toc: true
    toc_depth: 6
---

Ready to roll: 4 July 2023

TODO:
- Run Models again using the var_complete gm??

# Questions for methods and results

### ***How to correct for mass?***  
  - script = `Mass_Correction_Compare.Rmd`
  - Compare LM to GM (which models? all?)
    - use effect size, and ?bayes_r2? Loo?
      - script = `Mass_Correction_Compare.Rmd`
      - Looks great! lm better than gm, but not by much
      - the strength and even direction of the mass correction change when adding interaction term.
  
### ***What are the Indices Doing?***
  - How are indices correcting or not correcting for mass?
    - Results plotted in `Plots/Binary_Int_Mass_Effects.pdf` and the no-'Int' version
    - Indices generally limit the effect of body size on the relationship between phenotype and climbing
    - Several interesting points:
      - Crural Index in particular still maintains a strong body-size correlation that needs to be corrected for.
      - Less so, but still substantial, in BI, HEB, HRI, IM, MRI, OLI, PRI, & PES(2)
      - Geometric Mean mass effects are stronger, meaning that gm does less to remove the body size confound.
      
### **How to best describe climbing?***
  - we used binary, and a couple ordinal schemes
    - ordinal schemes resulted in few scansorial species
    - logistic regression gives probabilities, which can be interpreted directly
    - hence binary made sense, but we tried ordinal too
      
### ***Which measures are good predictors?***
  - High slope values = (list)
  - ***BUT, phylogeny issue! Test known as "fossils"***
    - can't add new tips to phylogeny in prediction
    - this affects both fossil and unknown taxa
    - tested predictions of extant species, treating them as fossil species
      - found that 12 key measurements have accuracy values over 70%
    - *General statements* (tl;dr) = Digits are good!
    - If no digits, then humerus length, ulna/radius length, Olecranon length (esp OLI), and, for hind limbs, Femur length.
      
  - ***Can taxonomic information inform predictions?***
      - *Point estimate predictions improve with taxonomy, but uncertainty greatly increases*
      - For a model that uses phy + order + fam + species, do this:
        ```
        predict({{model}}, summary = T, 
        probs = c(0.055, 0.945),  
        re_formula = ~ (1|Order) + (1|Family) + (1|Genus_species), 
        resp = 'Locbin'
        )
        ```
      - This adds tremendous uncertainty to the fossil predictions 
         - they are (mostly) new families and orders and subclasses. Hmm. 
        
    
  - ***Locomotion in Fossils***
    - Our predictions are variable
    - Talk about individual taxa here
    - Talk about individual clades/families
      - ex: long metatarsals in glires vs. metatherians, mezozoics, and multi's
     









# Notes:
How much of the locomotor inference is driven by extremes? 


## Abstract / Summary

Locomotor variation has played a key role in the evolution of mammals, and the variation of locomotor modes in mammals is astounding. The numerous transitions to arboreality across mammals is especially interesting, and has been hypothesized to be key to the success of the radiation. As such, relating phenotype to locomotor mode, particularly climbing, has long been a goal of evolutionary ecology, both to better understand mammal diversity and to make locomotor inferences for taxa that lack information such as fossils. The postcranium of mammals is a particular target for gleaning locomotor information, and has a relatively strong presence in the fossil record. However, the efforts to predict locomotion from the skeleton have been hampered several issues: the vase phenotypic disparity among terrestrial mammals, differences in phenotypic signals of locomotion among clades, wide variety of phenotypic measurements available for inference, multiple different methods to incorporate body size into locomotor predictions, and the endless numbers of ways that locomotor mode can be described or categorized. To date, several broad trends have emerged yet there is no consensus on the best methods of measuring, describing, and predicting locomotion across mammals. Here we use a dataset of XXX measurements from XXX specimens of XXX species to investigate and compare a range of different locomotor categorization schemes, phenotypic measurements, and methods for conditioning on size and incorporating intraspecific variation and phylogenetic covariation to determine which suite of metrics can provide the most reliable and accurate estimates of locomotor mode, particularly climbing.

<br>

# Outline

### Introduction  

Stuff here  

### Methods  

##### Measurements  

##### Statistics  

- Interesting point is how ratios relate to linear measurements + size. Do they ultimately do a decent job at addressing the question, even though they are not as effective? That could mean that in a pinch (e.g. only 1-2 bones available) ratios could still be useful. We should quantify this. 

##### Fossil Predictions  

- In addition to fossils, are there some bizarre extant mammals that we could test? Maybe Sommeromys? And how would Rhyncomys & Echiothrix fare in the predictions? 

### Results  


### Discussion

##### Summary of similarities and difference among methods

##### Best practices given a particular data set   

<br>
<br>

## Important Citations not to Forget!
<br>
<br>

```{r}
library(lme4)
library(equatiomatic)
library(texPreview)
MANUS ~Hl*log_Mass+(1|Family)+(1|Order)
fm1 <- lmer(MANUS ~ Hl*log_Mass+(1|Family)+(1|Order), dat)
extract_eq(fm1) %>% tex_preview()

fm2 <- glm(Loc_bin ~ Hl*log_Mass, dat, family = binomial)
extract_eq(fm2) %>% tex_preview()
```

